config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  ####################### DEVISE ROUTES ################################

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }


  ####################### ADMINDS ROUTES ###############################
  namespace :admins do
    # get 'users/index', to: 'users#index', as: :users

    resources :users, only: %i[ index show destroy ]
    resources :articles

    resources :courses do
      delete 'unsubscribe/student/:student_id',
       to: 'courses#unsubscribe_student',
       on: :member,
       as: :unsubscribe
       
      resources :sections, except: %i[ show index ], shallow: true
    end


    namespace :courses do
      namespace :modules do
        patch ':id/move', to: 'course_modules#move', as: :move
        delete ':id/destroy', to: 'course_modules#destroy'

        resources :sections, only: [] do
          resources :pages, except: %i[ index ], shallow: true
          resources :quizzes, except: %i[ index ], shallow: true do
            delete :delete_attempts, to: 'quizzes#delete_attempts', on: :member
          end
        end



        resources :quizzes, only: [], module: 'quizzes' do
          resources :questions, except: %i[ index ], shallow: true
        end


        scope :questions, module: 'quizzes' do
          patch ":id/move", to: 'questions#move', as: :move_question
        end
      end
    end
  end

  ######################### STUDENTS ROUTES ###############################
  namespace :students do
    get 'perfil/:id', to: 'users#show' 
    
    resources :articles, only: %i[ index show ]

    
    namespace :courses do
      namespace :modules do
        resources :pages, only: %i[ show ]
        resources :quizzes, only: %i[ show ] do
        end
      end

      resources :quizzes, module: :quiz, only: [] do
        get :start, to: 'attempts#start'
        post :finish, to: 'attempts#finish'
        get "attempts/:quiz_attempt_id/results", to: 'attempts#results', as: :results_attempt

      end

    end
    
    resources :courses, only: %i[ index show ] do
      post 'inscriptions', to: 'inscriptions#create', as: :inscriptions
      delete 'inscriptions', to: 'inscriptions#destroy'
    end
    get :my_courses, to: 'courses#my_courses'

  end

  ######################### PAGES ROUTES ###################################

  get :about, to: "pages#about"


end

app/controllers/students/courses/quiz/attempts_controller.rb
class Students::Courses::Quiz::AttemptsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_quiz
  before_action :lock_attempt, only: %i[ start finish ]
  before_action { lock_for_visible(@quiz.course_module.course) }
  before_action { lock_for_inscription(@quiz.course_module.course) }

  layout 'workstation'

  def start
    @questions = QuizQuestion.includes(:rich_text_description ,question_answers: :rich_text_answer)
      .where(module_quiz: @quiz).order(:position)
  end

  def finish
    @quiz_attempt = QuizAttempt.new(module_quiz: @quiz, user: current_user)

    responses_params[:quiz_attempts_attributes].each do |key, value|
      @quiz_attempt.question_attempts.build(value)
    end


    respond_to do |format|
      if @quiz_attempt.save && @quiz_attempt.set_sum_scores

        current_user.module_complete!(@quiz.course_module) if @quiz_attempt.approved?

        format.html {
          redirect_to students_courses_quiz_results_attempt_path(@quiz, @quiz_attempt), notice: "Prueba Finalizada"
        }

      else
        format.html { render :start, status: :unprocessable_entity }
      end
    end

    
  end

  def results
    @quiz_attempt = QuizAttempt.includes(question_attempts: [:quiz_question, { question_answer: [:rich_text_answer, :rich_text_feedback] }])
    .where(id: params[:quiz_attempt_id], user: current_user).first
  end



  private

  def set_quiz
    @quiz = ModuleQuiz.find(params[:quiz_id])
    lock_for_visible(@quiz.course_module.course)
  end

  def lock_attempt
    if current_user.module_completation?(@quiz.course_module)
      redirect_to students_courses_modules_quiz_path(@quiz), alert: 'Ya has completado este cuestionario'
    end
  end

  def responses_params
    params.require(:responses).permit(quiz_attempts_attributes: [:quiz_question_id, :question_answer_id])
  end


end

app/helpers/students/courses/quiz/question_attempts_helper.rb
module Students::Courses::Quiz::QuestionAttemptsHelper
end

app/views/students/courses/quiz/attempts/results.html.haml
.mb-4
	= render 'shared/header_simple', text: 'Resultados', url: students_courses_modules_quiz_path(@quiz)

.mx-auto.w-full{:class => "md:w-2/3"}
	.mb-4
		.overflow-hidden.bg-white.shadow.sm:rounded-lg
			.px-4.py-5.sm:px-6
				%h3.text-lg.font-medium.leading-6.text-gray-900 Resultados
				%p.mt-1.max-w-2xl.text-sm.text-gray-500 Resumen
			.border-t.border-gray-200
				%dl
					.bg-gray-50.px-4.py-5.sm:grid.sm:grid-cols-3.sm:gap-4.sm:px-6
						%dt.text-sm.font-medium.text-gray-500 Nombre del cuestionario
						%dd.mt-1.text-sm.text-gray-900.sm:col-span-2.sm:mt-0= @quiz.title
					
					.bg-white.px-4.py-5.sm:grid.sm:grid-cols-3.sm:gap-4.sm:px-6
						%dt.text-sm.font-medium.text-gray-500 Valor general del cuestionario
						%dd.mt-1.text-sm.text-gray-900.sm:col-span-2.sm:mt-0= @quiz.value
					
					.bg-gray-50.px-4.py-5.sm:grid.sm:grid-cols-3.sm:gap-4.sm:px-6
						%dt.text-sm.font-medium.text-gray-500 Puntaje minimo aprobatorio
						%dd.mt-1.text-sm.text-gray-900.sm:col-span-2.sm:mt-0= @quiz.min_value

					.bg-white.px-4.py-5.sm:grid.sm:grid-cols-3.sm:gap-4.sm:px-6
						%dt.text-sm.font-medium.text-gray-500 Valor total de las preguntas
						%dd.mt-1.text-sm.text-gray-900.sm:col-span-2.sm:mt-0= @quiz.sum_values

					.bg-gray-50.px-4.py-5.sm:grid.sm:grid-cols-3.sm:gap-4.sm:px-6
						%dt.text-sm.font-medium.text-gray-500 Puntaje total de las preguntas obtenido
						%dd.mt-1.text-sm.text-gray-900.sm:col-span-2.sm:mt-0= @quiz_attempt.sum_scores

					.bg-white.px-4.py-5.sm:grid.sm:grid-cols-3.sm:gap-4.sm:px-6
						%dt.text-sm.font-medium.text-gray-500 Puntaje General
						%dd.mt-1.text-sm.text-gray-900.sm:col-span-2.sm:mt-0= "#{@quiz_attempt.result_quiz}/#{@quiz.value}"

					.bg-gray-50.px-4.py-5.sm:grid.sm:grid-cols-3.sm:gap-4.sm:px-6
						%dt.text-sm.font-medium.text-gray-500 Estado
						%dd.mt-1.text-sm.text-gray-900.sm:col-span-2.sm:mt-0
							- if @quiz_attempt.approved?
								%span.text-lg.text-green-600.font-bold Aprobado
							- else
								%span.text-lg.text-red-600.font-bold Reprobado


	.mb-4
		.overflow-x-scroll
			%table.w-full.rounded-t-lg.text-white.bg-rose-700
				%thead
					%tr.text-left.border-b-2.border-black.font-bold
						%th.px-4.py-3 #
						%th.px-4.py-3 Pregunta
						%th.px-4.py-3 Respuesta
						%th.px-4.py-3 Retroalimentacion
						%th.px-4.py-3 Puntos
						%th.px-4.py-3 Calificacion
				%tbody
					- @quiz_attempt.question_attempts.each_with_index do |question_attempt, index|
						%tr.font-semibold{ class: index.even? ? 'bg-white' : 'bg-gray-50' }
							%td.px-4.py-3.border-b.border-black.text-black= index + 1
							%td.px-4.py-3.border-b.border-black.text-black= question_attempt.quiz_question.title
							%td.px-4.py-3.border-b.border-black.text-black
								= question_attempt.question_answer.answer
							%td.px-4.py-3.border-b.border-black.text-black
								- if question_attempt.question_answer.feedback.blank?
									%span No posee retroalimentacion
								- else
									= question_attempt.question_answer.feedback
							%td.px-4.py-3.border-b.border-black.text-black= "#{question_attempt.real_score}/#{question_attempt.max_score}"
							%td.px-4.py-3.border-b.border-black.text-black= question_attempt.result_question
				%tfoot
					%tr.bg-white.font-semibold
						%td.px-4.py-3.bg-transparent
						%td.px-4.py-3.bg-transparent
						%td.px-4.py-3.bg-transparent
						%td.px-4.py-3.bg-transparent
						%td.px-4.py-3.bg-transparent
						%td.px-4.py-3.border-l.border-b.border-black.text-rose-900.text-xl= @quiz_attempt.result_quiz

app/views/students/courses/quiz/attempts/start.html.haml
.mb-4
	= render 'shared/header_module', model: @quiz, url: students_courses_modules_quiz_path(@quiz)


.mx-auto.w-full{:class => "md:w-2/3"}
	.mb-4
		%h1.font-bold.text-2xl.text-rose-800 Cuestionario

	.mb-4

		= form_with(url: students_courses_quiz_finish_path(@quiz)) do |form|

			.mb-4.border-b.border-black

				%ul#questions-tab.flex.gap-4.-mb-px.text-sm.font-medium.text-center.overflow-x-scroll.text-rose-600{
					role: 'tablist',
					data: { 'tabs-toggle': '#questions-tab-content' }
				}

					- @questions.order(:position).each_with_index do |question, index|

						%li{ role: 'presentation' }
							%button{
								id: "question-#{index + 1}",
								role: 'tab',
								type: 'button',
								class: 'w-max inline-block p-4 rounded-t-lg font-bold',
								data: { 'tabs-target': "#content-question-#{index + 1}" }
							}

								= "Pregunta #{index + 1}"


			#questions-tab-content.mb-6
				- @questions.each_with_index do |question, index|
					.hidden.p-4.rounded-lg.bg-gray-50{
						id: "content-question-#{index + 1}",
						role: 'tabpanel',
					}
						= form.hidden_field "responses[quiz_attempts_attributes][#{index + 1}][quiz_question_id]", value: question.id 

						.flex.flex-col.items-center.gap-6
							%p.text-md.text-purple-700.font-bold= question.title

							= question.description
						%hr.border.border-black.mb-8

						.flex.flex-col.gap-6
							- answers = question.question_answers.shuffle

							= form.collection_radio_buttons "responses[quiz_attempts_attributes][#{index + 1}][question_answer_id]",
							 answers,
							 :id,
							 :answer,
							 { checked: answers.first.id },
							 { class: '' } do |radio|

								.flex.items-center.mb-4.gap-2
									= radio.radio_button
									= radio.label


			= form.submit 'Enviar Cuestionario', class: 'text-white bg-rose-700 hover:bg-rose-800 focus:ring-4 focus:outline-none focus:ring-rose-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center'