config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  ####################### DEVISE ROUTES ################################

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }


  ####################### ADMINDS ROUTES ###############################
  namespace :admins do
    # get 'users/index', to: 'users#index', as: :users

    resources :users, only: %i[ index show destroy ]
    resources :articles

    resources :courses do
      delete 'unsubscribe/student/:student_id',
       to: 'courses#unsubscribe_student',
       on: :member,
       as: :unsubscribe
       
      resources :sections, except: %i[ show index ], shallow: true
    end


    namespace :courses do
      namespace :modules do
        patch ':id/move', to: 'course_modules#move', as: :move
        delete ':id/destroy', to: 'course_modules#destroy'

        resources :sections, only: [] do
          resources :pages, except: %i[ index ], shallow: true
          resources :quizzes, except: %i[ index ], shallow: true do
            delete :delete_attempts, to: 'quizzes#delete_attempts', on: :member
          end
        end



        resources :quizzes, only: [], module: 'quizzes' do
          resources :questions, except: %i[ index ], shallow: true
        end


        scope :questions, module: 'quizzes' do
          patch ":id/move", to: 'questions#move', as: :move_question
        end
      end
    end
  end

  ######################### STUDENTS ROUTES ###############################
  namespace :students do
    get 'perfil/:id', to: 'users#show' 
    
    resources :articles, only: %i[ index show ]

    
    namespace :courses do
      namespace :modules do
        resources :pages, only: %i[ show ]
        resources :quizzes, only: %i[ show ] do
        end
      end

      resources :quizzes, module: :quiz, only: [] do
        get :start, to: 'attempts#start'
        post :finish, to: 'attempts#finish'
        get "attempts/:quiz_attempt_id/results", to: 'attempts#results', as: :results_attempt

      end

    end
    
    resources :courses, only: %i[ index show ] do
      post 'inscriptions', to: 'inscriptions#create', as: :inscriptions
      delete 'inscriptions', to: 'inscriptions#destroy'
    end
    get :my_courses, to: 'courses#my_courses'

  end

  ######################### PAGES ROUTES ###################################

  get :about, to: "pages#about"


end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  role                   :integer          default("student"), not null
#  username               :string           not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  ################# COURSE USER RELATIONS ##################
  has_many :courses_users, dependent: :destroy
  has_many :courses, through: :courses_users
  
  ################# COURSE MODULE COMPLETATION RELATIONS ##################
  has_many :course_module_completations, dependent: :destroy
  
  has_many :course_modules, through: :course_module_completations

  ################ QUIZ ATTEMPT RELATION ##################################
  has_many :quiz_attempts, dependent: :destroy

  ###################### DEVISE MODULES ####################
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ################# ROLE ENUM DEFINITION ##################
  enum :role, { admin: 0, student: 1 }, default: :student


  ################# VALIDATIONS ###########################
  validates :username, presence: true

  ################# PUBLIC METHODS ########################

  # Verifica si un usuario esta incrito en un curso o no.
  # @param course [Course]
  # @return [True|False]
  def course_inscript?(course)
    self.courses.exists?(course.id)
  end

  # Verifica si un usuario completo un modulo de curso o no
  # @param course_module [CourseModule]
  # @return [True|False]
  def module_completation?(course_module)
    self.course_module_completations.exists?(course_module_id: course_module.id, completed: true)
  end

  # Verifica si un usuario competo un modulo de curso,
  # De no tener completado el modulo, entonces crear un
  # registro en la base de datos completando el modulo
  # Si ya completo ese modulo entonces no realiza ninguna accion adicional
  # @param course_module [CourseModule]
  # @return [CourseModuleCompletation]
  def module_complete!(course_module)
    unless module_completation?(course_module)
      complete = self.course_module_completations.build(course_id: course_module.course_id ,course_module:, completed: true)

      complete.save
    end
  end


  # Calcula el progreso de un usuario en un curso dado
  # usando los modulos de dicho curso como referencia
  # @param course [Course]
  # @return [Float]
  def course_progress(course)
    total_modules_course = course.course_modules.size
    modules_complete = self.course_module_completations.select { |e| e.course_module.course_id == course.id }.size

    return (modules_complete * 100) / total_modules_course
  end

  # Verifica si un curso ha sido completado por un usuario
  # @params course [Course]
  # @return [Course]
  def course_completation?(course)
    self.courses_users.exists?(course_id: course.id, completed: true)
  end

  # Devuelve el regitro de la base de datos, ya sea que este
  # completado o no
  # @param course [Course]
  # @return [CourseCompletation]
  def course_completation(course)
    self.courses_users.select { |e| e.course_id == course.id }.first
  end

  # Desinscribe a un usuario de un curso: Elimina su inscripcion,
  # sus modulos completados, sus cursos completados
  # su registro en los cuestionarios, sus respuestas a los cuestionarios,
  # y su progreso general en el curso
  # @param course [Course]
  # @return [True|False]
  def desinscription_course(course)
    inscripcion = CoursesUser.find_by(user_id: self.id, course: course)
    modules_completations = self.course_module_completations.select do |e|
      e.course_module.course_id == course.id
    end

    quiz_attempts = self.quiz_attempts.select do |e|
      e.module_quiz.course_id == course.id
    end

    if inscripcion.destroy && modules_completations.each(&:destroy) && quiz_attempts.each(&:destroy)
      true
    else
      false
    end
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin!
  before_action :set_user, only: %i[ show destroy ]
  layout 'workstation'

  def show; end

  def index
    @pagy, @users = pagy(User.all, items: 20)
  end

  def destroy
    if @user
      @user.destroy
      redirect_to admins_users_path, notice: 'Usuario Eliminado'
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end


end

app/controllers/students/users_controller.rb
class Students::UsersController < ApplicationController
  before_action :authenticate_user!
  layout 'workstation'

  def show
    @user = User.find(params[:id])
    redirect_to students_courses_path, alert: 'Acceso Denegado' if @user.admin?
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  layout false
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  layout :resolve_layout

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end


  private

  def resolve_layout
    case action_name
    when 'edit', 'update'
      'workstation'
    else
      false
    end
  end

  protected

  def after_update_path_for(resource)
    helpers.determine_courses_way
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  layout false
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/views/admins/users/index.html.haml
.mb-4
	= render 'shared/header_simple', text: 'Indice de Usuarios', url: :back

.overflow-x-scroll.mt-4
	%table.rounded-t-lg.m-5.mx-auto.text-white.bg-purple-700{ class: "w-5/6" }
		%thead
			%tr.text-left.border-b-2.border-purple-200.font-bold
				%th.px-4.py-3 #
				%th.px-4.py-3 Nombre de Usuario
				%th.px-4.py-3 Correo Electronico
				%th.px-4.py-3 Rol de Usuario
				%th.px-4.py-3 Fecha de Registro
				%th.px-4.py-3 Acciones
		%tbody
			- @users.order(:role).each_with_index do |user, index|
				- if user.admin?
					%tr.font-semibold.text-black{ class: index.even? ? 'bg-white' : 'bg-gray-50' }
						%td.px-4.py-3.border-b.border-black= index + 1
						%td.px-4.py-3.border-b.border-black= user.username
						%td.px-4.py-3.border-b.border-black= user.email
						%td.px-4.py-3.border-b.border-black= t("user.role.#{user.role}")
						%td.px-4.py-3.border-b.border-black= user.created_at.to_date
						%td.px-4.py-3.border-b.border-black
							.flex.justify-center.items-center.gap-4
								%i.fa-solid.fa-trash.opacity-50{ title: "Este usuario no se puede eliminar" }

								= link_to admins_user_path(user), 
									class: 'hover:text-sky-500 text-lg cursor-pointer',
									title: 'Inspeccionar Usuario' do
									%i.fa-solid.fa-eye
				- else
					%tr.font-semibold.text-black{ class: index.even? ? 'bg-white' : 'bg-gray-50' }
						%td.px-4.py-3.border-b.border-black= index + 1
						%td.px-4.py-3.border-b.border-black= user.username
						%td.px-4.py-3.border-b.border-black= user.email
						%td.px-4.py-3.border-b.border-black= t("user.role.#{user.role}")
						%td.px-4.py-3.border-b.border-black= user.created_at.to_date
						%td.px-4.py-3.border-b.border-black
							.flex.justify-center.items-center.gap-4
								= button_to admins_user_path(user),
								 { class: "hover:text-red-500 text-lg cursor-pointer",
									method: :delete,
									data: { turbo_confirm: '¿Estas Seguro que quieres eliminar este usuario?' },
									title: 'Eliminar Usuario' } do

									%i.fa-solid.fa-trash

								= link_to admins_user_path(user), 
									class: 'hover:text-sky-500 text-lg cursor-pointer',
									title: 'Inspeccionar Usuario' do
									%i.fa-solid.fa-eye




- if @pagy.pages > 1
	.text-center
		!= pagy_nav(@pagy, link_extra: 'data-turbo-action="advance"')

app/views/admins/users/show.html.haml
.mb-4
  = render 'shared/header_simple', text: 'Inspeccion de Usuario', url: :back

.mx-auto.w-full{:class => "md:w-2/3"}
  .overflow-hidden.bg-purple-800.shadow.sm:rounded-lg.my-4
    .px-4.py-5.sm:px-6
      %h3.text-lg.font-medium.leading-6.text-white Informacion de Usuario
      %p.mt-1.max-w-2xl.text-sm.text-white Informacion personal no sensible de los usuarios
    .border-t.border-gray-200
      %dl
        .bg-gray-50.px-4.py-5.sm:grid.sm:grid-cols-3.sm:gap-4.sm:px-6
          %dt.text-sm.font-medium.text-gray-500 Nombre de Usuario
          %dd.mt-1.text-sm.text-gray-900.sm:col-span-2.sm:mt-0= @user.username
        
        .bg-white.px-4.py-5.sm:grid.sm:grid-cols-3.sm:gap-4.sm:px-6
          %dt.text-sm.font-medium.text-gray-500 Direccion de Correo Electronico
          %dd.mt-1.text-sm.text-gray-900.sm:col-span-2.sm:mt-0= @user.email
        
        .bg-gray-50.px-4.py-5.sm:grid.sm:grid-cols-3.sm:gap-4.sm:px-6
          %dt.text-sm.font-medium.text-gray-500 Rol de Usuario
          %dd.mt-1.text-sm.text-gray-900.sm:col-span-2.sm:mt-0= t("user.role.#{@user.role}")
        
        .bg-white.px-4.py-5.sm:grid.sm:grid-cols-3.sm:gap-4.sm:px-6
          %dt.text-sm.font-medium.text-gray-500 Fecha de Registro
          %dd.mt-1.text-sm.text-gray-900.sm:col-span-2.sm:mt-0= @user.created_at
        
        .bg-gray-50.px-4.py-5.sm:grid.sm:grid-cols-3.sm:gap-4.sm:px-6
          %dt.text-sm.font-medium.text-gray-500 Ultima fecha de Actualizacion de datos
          %dd.mt-1.text-sm.text-gray-900.sm:col-span-2.sm:mt-0= @user.updated_at
        
        .bg-white.px-4.py-5.sm:grid.sm:grid-cols-3.sm:gap-4.sm:px-6
          %dt.text-sm.font-medium.text-gray-500 Cursos Inscritos
          %dd.mt-1.text-sm.text-gray-900.sm:col-span-2.sm:mt-0
            - if @user.courses.empty?
              No posee inscripciones
            - else
              %ul.divide-y.divide-gray-200.rounded-md.border.border-gray-200{role: "list"}
              - @user.courses.each do |course|
                %li.flex.items-center.justify-between.py-3.pl-3.pr-4.text-sm
                  .flex.w-0.flex-1.items-center
                    %i.fa-solid.fa-book.flex-shrink-0.text-purple-400
                    %span.ml-2.w-0.flex-1.truncate= course.name
                  .ml-4.flex-shrink-0
                    = link_to admins_course_path(course),
                     class: 'font-medium text-indigo-600 hover:text-purple-500' do
                      %i.fa-solid.fa-eye{ title: 'Ir al curso' }

        .bg-gray-50.px-4.py-5.sm:grid.sm:grid-cols-3.sm:gap-4.sm:px-6
          %dt.text-sm.font-medium.text-gray-500 Completados
          %dd.mt-1.text-sm.text-gray-900.sm:col-span-2.sm:mt-0
            - if @user.courses_users.select{ |e| e.completed == true }.empty?
              No ha completado ningun curso
            - else
              %ul.divide-y.divide-gray-200.rounded-md.border.border-gray-200{role: "list"}
              - @user.courses_users.each do |completation|
                - if completation.completed
                  %li.flex.items-center.justify-between.py-3.pl-3.pr-4.text-sm
                    .flex.w-0.flex-1.items-center
                      %i.fa-solid.fa-book.flex-shrink-0.text-purple-400
                      %span.ml-2.w-0.flex-1.truncate= completation.course.name
                    .ml-4.flex-shrink-0
                      = link_to admins_course_path(completation.course),
                       class: 'font-medium text-indigo-600 hover:text-purple-500' do
                        %i.fa-solid.fa-eye{ title: 'Ir al curso' }