config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  ####################### DEVISE ROUTES ################################

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }


  ####################### ADMINDS ROUTES ###############################
  namespace :admins do
    # get 'users/index', to: 'users#index', as: :users

    resources :users, only: %i[ index show destroy ]
    resources :articles

    resources :courses do
      delete 'unsubscribe/student/:student_id',
       to: 'courses#unsubscribe_student',
       on: :member,
       as: :unsubscribe
       
      resources :sections, except: %i[ show index ], shallow: true
    end


    namespace :courses do
      namespace :modules do
        patch ':id/move', to: 'course_modules#move', as: :move
        delete ':id/destroy', to: 'course_modules#destroy'

        resources :sections, only: [] do
          resources :pages, except: %i[ index ], shallow: true
          resources :quizzes, except: %i[ index ], shallow: true do
            delete :delete_attempts, to: 'quizzes#delete_attempts', on: :member
          end
        end



        resources :quizzes, only: [], module: 'quizzes' do
          resources :questions, except: %i[ index ], shallow: true
        end


        scope :questions, module: 'quizzes' do
          patch ":id/move", to: 'questions#move', as: :move_question
        end
      end
    end
  end

  ######################### STUDENTS ROUTES ###############################
  namespace :students do
    get 'perfil/:id', to: 'users#show' 
    
    resources :articles, only: %i[ index show ]

    
    namespace :courses do
      namespace :modules do
        resources :pages, only: %i[ show ]
        resources :quizzes, only: %i[ show ] do
        end
      end

      resources :quizzes, module: :quiz, only: [] do
        get :start, to: 'attempts#start'
        post :finish, to: 'attempts#finish'
        get "attempts/:quiz_attempt_id/results", to: 'attempts#results', as: :results_attempt

      end

    end
    
    resources :courses, only: %i[ index show ] do
      post 'inscriptions', to: 'inscriptions#create', as: :inscriptions
      delete 'inscriptions', to: 'inscriptions#destroy'
    end
    get :my_courses, to: 'courses#my_courses'

  end

  ######################### PAGES ROUTES ###################################

  get :about, to: "pages#about"


end

app/controllers/admins/courses/modules/course_modules_controller.rb
class Admins::Courses::Modules::CourseModulesController < ApplicationController
	before_action :authenticate_user!
	before_action :authenticate_admin!
	before_action :set_course_module


	def move
		@course_module.insert_at(params[:position].to_i)
		head :ok
	end

	def destroy
		@course_module.destroy

		respond_to do |format|
			format.html { redirect_to admins_course_path(@course_module.course_id), alert: 'Modulo Eliminado' }
			format.turbo_stream { flash.now[:alert] = 'Modulo Eliminado' }
		end
	end

	private

	def set_course_module
		@course_module = CourseModule.find(params[:id])
	end
end

app/controllers/admins/courses/modules/pages_controller.rb
class Admins::Courses::Modules::PagesController < ApplicationController
	before_action :authenticate_user!
	before_action :authenticate_admin!
	before_action :set_section, only: %i[ new create ]
	before_action :set_page, only: %i[ show edit update destroy ]
	
	layout 'workstation'

	def new
		@page = @section.module_pages.build
	end

	def create
		@page = @section.module_pages.build(pages_params)
		@page.course_module = CourseModule.new(course_id: @section.course_id, section_id: @section.id)
		
		respond_to do |format|
			if @page.save
				format.html { redirect_to admins_course_path(@section.course_id), notice: 'Modulo Pagina: Creado' }				
			else
				format.html { render :new, status: :unprocessable_entity }
			end
		end
	end

	def show
	end

	def edit
	end

	def update
		respond_to do |format|
			if @page.update(pages_params)
				format.html {
					redirect_to admins_course_path(@page.course_module.course_id), notice: 'Modulo Pagina: Actualizado'
				}
			else
				format.html {
					render :edit, status: :unprocessable_entity
				}
			end
		end
	end

	def destroy
		@page.destroy

		respond_to do |format|
			format.html {
				redirect_to admins_course_path(@page.course_module.course_id), notice: 'Modulo Pagina: Eliminado'
			}
		end
	end


	private

	def set_section
		@section = Section.find(params[:section_id])
	end

	def set_page
		@page = ModulePage.find(params[:id])
	end

	def pages_params
    params.require(:module_page).permit(:title, :content)
  end
end

app/controllers/admins/courses/modules/quizzes/questions_controller.rb
class Admins::Courses::Modules::Quizzes::QuestionsController < ApplicationController
	before_action :authenticate_user!
	before_action :authenticate_admin!
	before_action :set_quiz, only: %i[ new create ]
	before_action :set_question, except: %i[ new create ]
	before_action :lock_modify, except: %i[ move ]

	layout 'workstation'

	def new
		case params[:type]
		when 'multichoice'
			@question = @quiz.quiz_questions.build

			4.times { @question.question_answers.build }
		when 'truefalse'
			@question = @quiz.quiz_questions.build(question_type: 'truefalse')

			@question.question_answers.build(answer: 'Verdadero')
			@question.question_answers.build(answer: 'Falso')
		end

	end

	def create
		@question = @quiz.quiz_questions.build(questions_params)
		respond_to do |format|

			if @question.save
				format.html {
					redirect_to admins_courses_modules_quiz_path(@quiz), notice: 'Pregunta de Cuestionario: Creada'
				}
			else
				format.html { render :new, status: :unprocessable_entity }
			end
			
		end
	end

	def edit
	end

	def update
		respond_to do |format|
			if @question.update(questions_params)
				format.html {
					redirect_to admins_courses_modules_quiz_path(@question.module_quiz_id), notice: 'Pregunta de Cuestionario: Actualizada'
				}
			else
				format.html {
					render :edit, status: :unprocessable_entity
				}
			end
		end
	end

	def destroy
		@question.destroy

		respond_to do |format|
			format.html {
				redirect_to admins_courses_modules_quiz_path(@question.module_quiz_id), alert: 'Pregunta de Cuestionario: Eliminada'
			}
		end
	end


	def move
		@question.insert_at(params[:position].to_i)
		head :ok
	end


	private

	def set_quiz
		@quiz = ModuleQuiz.find(params[:quiz_id])
	end

	def set_question
		@question = QuizQuestion.includes(question_answers: [:rich_text_answer, :rich_text_feedback])
			.where(id: params[:id]).first
	end

	def questions_params
		params.require(:quiz_question).permit(
			:title,
			:description,
			:score,
			:question_type,
			question_answers_attributes: [:id, :answer, :feedback, :fraction]
		)
	end

	def lock_modify
		if @quiz.nil?
			redirect_to admins_courses_modules_quiz_path(@question.module_quiz),
			 alert: 'No puedes modificar un cuestionario que ya ha sido respondido' if @question.module_quiz.quiz_attempts.any? 
			
		else
			redirect_to admins_courses_modules_quiz_path(@quiz),
			 alert: 'No puedes modificar un cuestionario que ya ha sido respondido' if @quiz.quiz_attempts.any?
		end
	end
end

app/controllers/admins/courses/modules/quizzes_controller.rb
class Admins::Courses::Modules::QuizzesController < ApplicationController
	before_action :authenticate_user!
	before_action :authenticate_admin!
	before_action :set_section, only: %i[ new create ]
	before_action :set_quiz, except: %i[ new create ]
	before_action :lock_for_attempts, only: %i[ edit update ]

	layout 'workstation'

	def new
		@quiz = @section.module_quizzes.build
	end

	def create
		@quiz = @section.module_quizzes.build(quizzes_params)
		@quiz.course_module = CourseModule.new(course_id: @section.course_id, section_id: @section.id)

		respond_to do |format|
			if @quiz.save
				format.html { redirect_to admins_courses_modules_quiz_path(@quiz), notice: 'Modulo Cuestionario: Creado' }				
			else
				format.html { render :new, status: :unprocessable_entity }
			end
		end
	end

	def show
	end

	def edit
	end

	def update
		respond_to do |format|
			if @quiz.update(quizzes_params)
				format.html {
					redirect_to admins_course_path(@quiz.course_module.course_id), notice: 'Modulo Cuestionario: Actualizado'
				}
			else
				format.html {
					render :edit, status: :unprocessable_entity
				}
			end
		end
	end

	def destroy
		@quiz.destroy

		respond_to do |format|
			format.html {
				redirect_to admins_course_path(@quiz.course_module.course_id), notice: 'Modulo Cuestionario: Eliminado'
			}
		end
	end

	def delete_attempts
		attempts = QuizAttempt.where(module_quiz: @quiz)
		completations = CourseModuleCompletation.where(course_module: @quiz.course_module)

		respond_to do |format|

			unless attempts.empty?
				attempts.destroy_all
				completations.destroy_all
				
				format.html { redirect_to admins_courses_modules_quiz_path(@quiz), alert: 'Intentos Eliminados' }
			end
		end
	end

	private

	def set_section
		@section = Section.find(params[:section_id])
	end

	def set_quiz
		@quiz = ModuleQuiz.find(params[:id])
	end

	def lock_for_attempts
		if @quiz.quiz_attempts.any?
			respond_to do |format|
				msg = "No puedes editar un cuestionario que ya ha sido respondido"
				format.turbo_stream {
					flash.now[:alert] = msg
					render turbo_stream: helpers.render_flash_messages
				}

				format.html { redirect_to admins_course_path(@quiz.course_id), alert: msg }
			end
			
		end
	end

	def quizzes_params
    params.require(:module_quiz).permit(:title, :description, :min_value, :value)
  end
end

app/controllers/students/courses/modules/pages_controller.rb
class Students::Courses::Modules::PagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_page
  before_action { lock_for_visible(@page.course_module.course) }
  before_action { lock_for_inscription(@page.course_module.course) }


  layout 'workstation'

  def show
    current_user.module_complete!(@page.course_module)
  end


  private

  def set_page
    @page = ModulePage.find(params[:id])
  end
end

app/controllers/students/courses/modules/quizzes_controller.rb
class Students::Courses::Modules::QuizzesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_quiz
  before_action { lock_for_visible(@quiz.course_module.course) }
  before_action { lock_for_inscription(@quiz.course_module.course) }

  layout 'workstation'

  def show
    @user_attempts = QuizAttempt.where(module_quiz: @quiz, user: current_user).all
  end

  private

  def set_quiz
    @quiz = ModuleQuiz.find(params[:id])
  end

  
end

app/helpers/admins/courses/modules/course_modules_helper.rb
module Admins::Courses::Modules::CourseModulesHelper
end

app/helpers/admins/courses/modules/pages_helper.rb
module Admins::Courses::Modules::PagesHelper
end

app/helpers/admins/courses/modules/quizzes/questions_helper.rb
module Admins::Courses::Modules::Quizzes::QuestionsHelper
end

app/helpers/admins/courses/modules/quizzes_helper.rb
module Admins::Courses::Modules::QuizzesHelper
end

app/helpers/students/courses/modules/course_module_completions_helper.rb
module Students::Courses::Modules::CourseModuleCompletionsHelper
end

app/helpers/students/courses/modules/course_modules_helper.rb
module Students::Courses::Modules::CourseModulesHelper
end

app/helpers/students/courses/modules/pages_helper.rb
module Students::Courses::Modules::PagesHelper
end

app/helpers/students/courses/modules/quizzes_helper.rb
module Students::Courses::Modules::QuizzesHelper
end

app/views/admins/courses/modules/quizzes/_form.html.haml
= form_with(model: model, url: url) do |form|
  = render 'shared/form_errors', model:

  .mb-5
    .relative.z-0.w-full.group
      = form.text_field :title, class: "block px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-nonefocus:outline-none focus:ring-0 focus:border-purple-600 peer py-2.5", title: 'Titulo del cuestionario'

      = form.label :title, class: 'peer-focus:font-medium absolute text-sm text-gray-500 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 peer-focus:left-0 peer-focus:text-purple-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6 origin-[0]'


  .mb-5
    = form.label :description
    = form.rich_text_area :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full trix-editor bg-gray-50"

  .mb-5
    .relative.z-0.w-full.group
      = form.number_field :value, class: "block px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-nonefocus:outline-none focus:ring-0 focus:border-purple-600 peer py-2.5", title: 'Valor general del cuestionario'

      = form.label :value, class: 'peer-focus:font-medium absolute text-sm text-gray-500 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 peer-focus:left-0 peer-focus:text-purple-600 peer-focus:dark:text-purple-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6 origin-[0]'

  .mb-5
    .relative.z-0.w-full.group
      = form.number_field :min_value, class: "block px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-nonefocus:outline-none focus:ring-0 focus:border-purple-600 peer py-2.5", title: 'Valor minimo aprobatorio'

      = form.label :min_value, class: 'peer-focus:font-medium absolute text-sm text-gray-500 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 peer-focus:left-0 peer-focus:text-purple-600 peer-focus:dark:text-purple-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6 origin-[0]'

  .inline
    = form.submit class: "text-white bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:outline-none focus:ring-purple-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center"

app/views/admins/courses/modules/quizzes/edit.es.html.haml
%h1 Editar Cuestionario

= render 'form', model: @quiz, url: admins_courses_modules_quiz_path(@quiz)

app/views/admins/courses/modules/quizzes/edit.html.haml
.mb-4
	= render 'shared/header_simple', text: 'Editar Cuestionario', url: admins_course_path(@quiz.course_id)

.w-full.flex.justify-center
	.w-full{ class: 'md:w-3/4' }
		= render 'form', model: @quiz, url: admins_courses_modules_quiz_path(@quiz)

app/views/admins/courses/modules/quizzes/new.html.haml
.mb-4
	= render 'shared/header_simple', text: 'Crear Cuestionario', url: admins_course_path(@section.course_id)

.w-full.flex.justify-center
	.w-full{ class: 'md:w-3/4' }
		= render 'form', model: @quiz, url: admins_courses_modules_section_quizzes_path(@section)

app/views/admins/courses/modules/quizzes/show.html.haml
.mb-4
	= render 'shared/header_module', model: @quiz, url: admins_course_path(@quiz.course_id)

.mx-auto.w-full{:class => "md:w-2/3"}

	-# Tab List
	.mb-4.border-b.border-black
		%ul#quiz-tab.flex.gap-4.-mb-px.text-sm.font-medium.text-center.overflow-x-scroll.text-rose-600{
			role: 'tablist',
			data: { 'tabs-toggle': '#quiz-tab-content' }
		}

			-#  Tab buttons
			%li{ role: 'presentation' }
				%button{
					id: 'quiz-resume',
					role: 'tab',
					type: 'button',
					class: 'w-max inline-block p-4 rounded-t-lg font-bold',
					title: 'Informacion del Cuestionario',
					data: { 'tabs-target': '#tab-quiz-resume' }
				}
					Cuestionario

			%li{ role: 'presentation' }
				%button{
					id: 'quiz-attempts',
					role: 'tab',
					type: 'button',
					class: 'w-max inline-block p-4 rounded-t-lg font-bold',
					title: 'Informacion de Intentos de Estudiantes',
					data: { 'tabs-target': '#tab-quiz-attempts' }
				}
					Estudiantes


	-# Tab Panel
	#quiz-tab-content.mb-4
		-# Tab Panel 1: Quiz
		.hidden.p-4.rounded-lg.bg-gray-50{
			id: 'tab-quiz-resume',
			role: 'tabpanel'
		}

			.overflow-hidden.bg-rose-800.shadow.sm:rounded-lg.mb-4
				.px-4.py-5.sm:px-6
					%h3.text-lg.font-medium.leading-6.text-white Informacion del Cuestionario
					%p.mt-1.max-w-2xl.text-sm.text-white Resumen
				.border-t.border-gray-200
					%dl
						.bg-gray-50.px-4.py-5.sm:grid.sm:grid-cols-3.sm:gap-4.sm:px-6
							%dt.text-sm.font-medium.text-gray-500 Nombre del cuestionario
							%dd.mt-1.text-sm.text-gray-900.sm:col-span-2.sm:mt-0= @quiz.title
						
						.bg-white.px-4.py-5.sm:grid.sm:grid-cols-3.sm:gap-4.sm:px-6
							%dt.text-sm.font-medium.text-gray-500 Valor general del cuestionario
							%dd.mt-1.text-sm.text-gray-900.sm:col-span-2.sm:mt-0= @quiz.value
						
						.bg-gray-50.px-4.py-5.sm:grid.sm:grid-cols-3.sm:gap-4.sm:px-6
							%dt.text-sm.font-medium.text-gray-500 Valor minimo aprobatorio
							%dd.mt-1.text-sm.text-gray-900.sm:col-span-2.sm:mt-0= @quiz.min_value

						.bg-white.px-4.py-5.sm:grid.sm:grid-cols-3.sm:gap-4.sm:px-6
							%dt.text-sm.font-medium.text-gray-500 Conteo global de intentos
							%dd.mt-1.text-sm.text-gray-900.sm:col-span-2.sm:mt-0= @quiz.quiz_attempts.size

						- if @quiz.quiz_attempts_any?
							.bg-gray-50.px-4.py-5.sm:grid.sm:grid-cols-3.sm:gap-4.sm:px-6
								%dt.text-sm.font-medium.text-gray-500 Advertencia
								%dd.mt-1.text-sm.text-gray-900.sm:col-span-2.sm:mt-0
									.flex.flex-col.gap-4
										%p
											No puedes modificar un cuestionario que ya ha sido respondido por estudiantes
											%span.text-xs.text-red-600 (Tienes que eliminar todos los intentos de usuarios para poder editar)

										= link_to 'Borrar intentos de usuarios',
											delete_attempts_admins_courses_modules_quiz_path(@quiz),
											class: 'text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center',
											data: { turbo_method: :delete, turbo_confirm: '¿Seguro?' }


			- if @quiz.quiz_attempts_any?
				%h2.font-bold.text-3xl.border-b-2.border-black Preguntas
			- else

				.flex.items-center.gap-4.border-b-2.border-black.mb-4
					%h1.font-bold.text-3xl Preguntas

					%div{ data: { controller: 'modal' } }
						= render(Modal::BtnComponent.new(title: 'Agregar Pregunta',
																		style: 'text-purple-600 text-3xl cursor-pointer')) do

							%i.fa-solid.fa-circle-plus


						= render(Modal::WindowComponent.new(header: 'Agregar Pregunta')) do
							.p-6.grid.grid-cols-2.gap-4
								%ul.flex.flex-col.gap-2{
									role: 'tablist',
									data: { 'tabs-toggle': '#question-descriptions' }
								}
									%li{ role: 'presentation' }
										%button#multichoice-tab.w-full.p-4.bg-purple-100.text-purple-600{
											role: 'tab',
											type: 'button',
											data: { 'tabs-target': '#multichoice' },
										}
											Opcion Multiple

									%li{ role: 'presentation' }
										%button#truefalse-tab.w-full.p-4.bg-purple-100.text-purple-600{
											role: 'tab',
											type: 'button',
											data: { 'tabs-target': '#truefalse' },
										}
											Verderaro o Falso


								#question-descriptions
									#multichoice.hidden.p-4.rounded-lg.bg-gray-50{"aria-labelledby" => "multichoice-tab", role: "tabpanel"}
										.flex.flex-col.gap-4
											.w-full.flex.flex-col.gap-4
												%h5.text-md.font-mono.text-pruple-700.self-center.underline Opcion Multiple
												%p.text-sm.text-gray-500
													Es un tipo de pregunta, donde el usuario debera escojer una respuesta entre un listado de respuestas posibles

											= link_to 'Registrar pregunta',
											 new_admins_courses_modules_quiz_question_path(@quiz, type: 'multichoice'),
											 class: 'text-white bg-rose-700 hover:bg-rose-800 focus:ring-4 focus:outline-none focus:ring-rose-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center'

									#truefalse.hidden.p-4.rounded-lg.bg-gray-50{"aria-labelledby" => "truefalse-tab", role: "tabpanel"}
										.flex.flex-col.gap-4
											.w-full.flex.flex-col.gap-4
												%h5.text-md.font-mono.text-pruple-700.self-center.underline Verdadero/Falso
												%p.text-sm.text-gray-500
													Es un tipo de pregunta, donde el usuario debera escojer segun el enunciado 2 opciones
													%span.text-green-600 Verdadero
													o
													%span.text-red-600 Falso

											= link_to 'Registrar pregunta',
											 new_admins_courses_modules_quiz_question_path(@quiz, type: 'truefalse'),
											 class: 'text-white bg-rose-700 hover:bg-rose-800 focus:ring-4 focus:outline-none focus:ring-rose-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center'


			- if @quiz.quiz_questions.any?
				%p.font-bold.text-xl.w-full.text-center= "Puntaje total de preguntas: #{@quiz.sum_values}"

				.overflow-x-scroll
					%table.rounded-t-lg.text-white.bg-rose-700.w-full
						%thead
							%tr.text-left.border-b-2.border-gray-200.font-bold
								%th.px-4.py-3 
								%th.px-4.py-3 Titulo
								%th.px-4.py-3 Puntacion
								%th.px-4.py-3 Tipo de Pregunta
								%th.px-4.py-3 Acciones
						%tbody{ data: { controller: 'drag-drop', 'drag-drop-handle-value': '.fa-up-down-left-right' } }
							- @quiz.quiz_questions.order(:position).each_with_index do |question, index|
								%tr.font-semibold.text-gray-900{
									id: dom_id(question),
									class: index.even? ? 'bg-white' : 'bg-gray-50',
									data: { item_id: question.id, move_url: admins_courses_modules_move_question_path(question) }
								}
									%td.px-4.py-3.border-b.border-gray-700
										%i.fa-solid.fa-up-down-left-right.text-xl.cursor-move.hover:text-rose-600{
											title: 'Arastra para reorganizar preguntas'
										}
									%td.px-4.py-3.border-b.border-gray-700
										- if @quiz.quiz_attempts_any?
											= question.title
										- else
											= link_to question.title, edit_admins_courses_modules_question_path(question), title: 'Editar Pregunta',class: 'hover:text-rose-600'
									%td.px-4.py-3.border-b.border-gray-700= question.score
									%td.px-4.py-3.border-b.border-gray-700= question.type
									%td.px-4.py-3.border-b.border-gray-700
										- unless @quiz.quiz_attempts_any?
											= button_to admins_courses_modules_question_path(question), { method: :delete, class: 'text-2xl font-bold text-gray-900 hover:text-red-500', title: 'Eliminar Pregunta', data: { turbo_confirm: 'Tambien se eliminara las respuestas de esta pregunta. ¿Seguro que quieres eliminar esta pregunta?' } } do

												%i.fa-solid.fa-trash



	-# Tab Panel 2: Quiz-Attempts
	.hidden.p-4.rounded-lg.bg-gray-50{
		id: 'tab-quiz-attempts',
		role: 'tabpanel'
	}
		%p.font-bold.text-xl.w-full.text-center Resumen de interacciones de estudiantes

		.overflow-x-scroll
			%table.rounded-t-lg.text-white.bg-rose-700.w-full
				%thead
					%tr.text-left.border-b-2.border-gray-200.font-bold
						%th.px-4.py-3 #
						%th.px-4.py-3 Usuario
						%th.px-4.py-3 N° Intentos
						%th.px-4.py-3 Mayor Puntaje Obtenido
				%tbody
					- @quiz.students_results.each_with_index do |student, index|
						%tr.font-semibold.text-gray-900{ class: index.even? ? 'bg-white' : 'bg-gray-50' }
							%td.px-4.py-3.border-b.border-gray-700= index + 1
							%td.px-4.py-3.border-b.border-gray-700
								= link_to student.user.username,
								 admins_user_path(student.user_id),
								 class: 'text-purple-600 hover:text-gray-800'
							%td.px-4.py-3.border-b.border-gray-700= student.attempts
							%td.px-4.py-3.border-b.border-gray-700= "#{student.score}/#{@quiz.sum_values}"